<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="false" CodeBehind="Admins.aspx.cs" Inherits="NathanWeb.Admin.Admins" %>
<asp:Content ID="Content1" ContentPlaceHolderID="phContent" runat="server">
<main>
    <h1>Admins</h1>

    <form runat="server">

        <asp:Button ID="btnAdd" runat="server" Text="Add Admin" OnClick="btnAdd_Click" />

        <asp:GridView ID="gvAdmins" runat="server" DataSourceID="dsAdmins" DataKeyNames="id"
            AutoGenerateColumns="false" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
            BorderStyle="None" CssClass="gridview"
            OnRowEditing="gvAdmins_RowEditing" OnRowUpdating="gvAdmins_RowUpdating">
            <Columns>
                <asp:BoundField HeaderText="id" DataField="id" ReadOnly="true" />
                <asp:BoundField HeaderText="username" DataField="username" />
                <asp:TemplateField HeaderText="password">
                    <ItemTemplate>•••</ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtPassword" runat="server" TextMode="Password" MaxLength="50" />
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:CheckBoxField HeaderText="active" DataField="active" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="dsAdmins" runat="server" ConnectionString="<%$ ConnectionStrings:dbConnection %>"
            SelectCommand="SELECT id,username,active FROM admins ORDER BY username"
            UpdateCommand="UPDATE admins SET username=@username,active=@active WHERE id=@id"
            DeleteCommand="DELETE FROM admins WHERE id=@id" />

    </form>
</main>
</asp:Content>
