<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="false" CodeBehind="Categories.aspx.cs" Inherits="NathanWeb.Admin.Categories" %>
<asp:Content ID="Content1" ContentPlaceHolderID="phContent" runat="server">
<main>
    <h1>Categories</h1>

    <form runat="server">

        <asp:Button ID="btnAdd" runat="server" Text="Add Tip" OnClick="btnAdd_Click"/>

        <asp:GridView ID="gvCategories" runat="server" DataSourceID="dsCategories"
            DataKeyNames="id" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
            BorderStyle="None" CssClass="gridview" >
        </asp:GridView>
        <asp:SqlDataSource ID="dsCategories" runat="server" ConnectionString="<%$ ConnectionStrings:dbConnection %>"
            SelectCommand="SELECT id,orderBy,name,active FROM categories ORDER BY active,name"
            UpdateCommand="UPDATE categories SET orderBy=@orderBy,name=@name,active=@active WHERE id=@id"
            DeleteCommand="DELETE FROM categories WHERE id=@id">
        </asp:SqlDataSource>
    </form>

</main>
</asp:Content>
