<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="false" CodeBehind="Tips.aspx.cs" Inherits="NathanWeb.Admin.Tips" %>
<asp:Content ID="Content1" ContentPlaceHolderID="phContent" runat="server">
<main>
    <h1>Tips</h1>

    <form runat="server">

        <asp:Button ID="btnAdd" runat="server" Text="Add Tip" OnClick="btnAdd_Click" />

        <asp:GridView ID="gvTips" runat="server" DataSourceID="dsTips" DataKeyNames="id"
            AutoGenerateColumns="false" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
            BorderStyle="None" CssClass="gridview">
            <Columns>
                <asp:BoundField HeaderText="id" DataField="id" ReadOnly="true" />
                <asp:BoundField HeaderText="orderBy" DataField="orderBy" />
                <asp:TemplateField HeaderText="category">
                    <ItemTemplate>
                        <%# HttpUtility.HtmlEncode(Eval("category")) %>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlCategory" runat="server"
                            DataSourceId="dsCategories" DataValueField="id" DataTextField="name"
                            SelectedValue='<%# Bind("categoryId") %>'/>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:BoundField HeaderText="title" DataField="title" />
                <asp:CheckBoxField HeaderText="active" DataField="active" />
                <asp:HyperLinkField Text="Edit Content" DataNavigateUrlFields="id" DataNavigateUrlFormatString="Tip?id={0}" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="dsTips" runat="server" ConnectionString="<%$ ConnectionStrings:dbConnection %>"
            SelectCommand="SELECT t.id,t.orderBy,t.categoryId,c.name category,t.title,t.active FROM tips t LEFT JOIN categories c ON c.id=t.categoryId ORDER BY t.active,t.orderBy"
            UpdateCommand="UPDATE tips SET orderBy=@orderBy,categoryId=@categoryId,title=@title,active=@active WHERE id=@id"
            DeleteCommand="DELETE FROM tips WHERE id=@id" />
        <asp:SqlDataSource ID="dsCategories" runat="server" ConnectionString="<%$ ConnectionStrings:dbConnection %>"
            SelectCommand="SELECT NULL id,'' name UNION SELECT id,name FROM categories ORDER BY name" />

    </form>

</main>
</asp:Content>
